// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

const isPostgre = (env('DATABASE_URL') || '').includes('postgre');

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: `prisma/migrations_${isPostgre ? 'postgre' : 'sqlite'}`,
  },
  datasource: {
    url: env('DATABASE_URL') || '',
  },
});
